### ISSUE TITLE
加载未定义控制器

### ISSUE THREAD

**Issue by admininfon** [wzxaini9/ThinkCMF-plugins#1]
插件报错了：
~~~
[1] ErrorException in AdminIndexController.php line 14
Class 'cmf\controller\PluginAdminBaseController' not found
~~~

// | Copyright (c) 2013-2014 http://www.thinkcmf.com All rights reserved.
// +----------------------------------------------------------------------
// | Author: Dean <zxxjjforever@163.com>
// +----------------------------------------------------------------------
namespace plugins\admin_journal\controller; //Demo插件英文名，改成你的插件英文就行了
**`use cmf\controller\PluginAdminBaseController;`**
class AdminIndexController extends PluginAdminBaseController
{    
    protected function _initialize()    
    {        
        $adminId = cmf_get_current_admin_id(); //获取后台管理员id，可判断是否登录        
        if (!empty($adminId)) {            
            $this->assign("admin_id", $adminId);        
        } else {            
            $this->error('未登录');
        }
​

**Comment by wzxaini9** [comment]
你的cmf是什么版本的?我查一下

**Comment by wzxaini9** [comment]
由于5.0.180123之前旧版本没有

PluginAdminBaseController

所以改为

PluginBaseController

以兼容旧版本
