### ISSUE TITLE
请问您的插件可以免费商用吗？

### ISSUE THREAD

**Issue by hedali1997** [wzxaini9/ThinkCMF-plugins#6]
请问您的插件可以免费商用吗？

**Comment by wzxaini9** [comment]
🙃🙃🙃可以免费给别人用。。。如果赚钱的话可以适当对开发者进行打赏吖。。。

**Comment by hedali1997** [comment]
好的，谢谢------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月12日(星期一) 下午4:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wzxaini9/ThinkCMF-plugins] 请问您的插件可以免费商用吗？ (#6)
